version: "3.9"
services:
  brighte-eats-api:
    build: .
    ports:
      - 3001:3000
    environment:
      DB_HOSTNAME: db
      DB_NAME: brighte-eats
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brighte-eats
    ports:
      - "5432:5432"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
